version: '2'

networks:
  hospital_network:
    name: hospital_network

services:
  redis1:
    image: 'redis:latest'
    container_name: redis.doctor.com
    command: redis-server --requirepass doctorpassword
    ports:
      - "6379:6379"
    networks:
      - hospital_network

  redis2:
    image: 'redis:latest'
    container_name: redis.laboratory.com
    command: redis-server --requirepass labpassword
    ports:
      - "6380:6379"
    networks:
      - hospital_network